#!/usr/bin/env bash
# Commits staged changes and either pushes directly to the target branch or
# opens a PR. Falls back to PR if direct push fails. Forces PR mode for major
# bumps (caller sets FORCE_PR=1). After a successful direct push or fresh
# replacement PR, closes any still-open PRs this automation opened for older
# bumps against the same target branch, so consumer repos don't accumulate
# stale bump PRs.
#
# Required env:
#   REPO              owner/name
#   TARGET_BRANCH     branch to update
#   NEW_TAG           e.g. v1.28.6
#   BUMP_LEVEL        patch|minor|major
#   FORCE_PR          1 to skip direct push (set for major bumps)
#   AUTO_MERGE        true|false (per-level setting from config)
#   GH_TOKEN          token of the bot (also exported as GITHUB_TOKEN for gh)
#
# Run from the root of the cloned target repo with the version rewrite already
# applied and `git add -A` already executed.
set -euo pipefail

# The caller captures this script's stdout to /tmp/result.json and parses it
# as JSON, so every chatty subprocess (git commit's "[branch sha] msg" line,
# git push progress, gh pr create's URL echo) must NOT leak to stdout.
# Reroute stdout to stderr for the whole script; the final jq writes the
# result via FD 3 (the original stdout).
exec 3>&1 1>&2

: "${REPO:?}" "${TARGET_BRANCH:?}" "${NEW_TAG:?}" "${BUMP_LEVEL:?}" "${GH_TOKEN:?}"
force_pr="${FORCE_PR:-0}"
auto_merge="${AUTO_MERGE:-false}"

# Committer identity and GPG signing are configured globally by the caller
# workflow (see crazy-max/ghaction-import-gpg in version-propagation.yml).
# Do NOT override here — that would replace the signing identity.

msg="chore(ci): bump shared-workflows to ${NEW_TAG}"
if [[ "$BUMP_LEVEL" != "major" ]]; then
  msg+=$'\n\n[skip ci]'
fi

git commit -m "$msg"

action="unknown"
url=""

if [[ "$force_pr" -eq 1 ]]; then
  open_pr=1
else
  if git push origin "HEAD:${TARGET_BRANCH}" 2>/tmp/push.err; then
    action="push"
    open_pr=0
  else
    echo "direct push failed, falling back to PR:" >&2
    cat /tmp/push.err >&2
    open_pr=1
  fi
fi

if [[ "$open_pr" -eq 1 ]]; then
  # The commit above may carry [skip ci] (added for the direct-push case, to
  # avoid re-triggering CI on a trivial bump). That's wrong for a PR: consumer
  # repos gate merging on required status checks, and [skip ci] means those
  # checks never run, leaving the PR permanently unmergeable. The rejected
  # direct push never landed anywhere, so amending here is safe.
  if [[ "$force_pr" -ne 1 ]]; then
    git commit --amend -m "chore(ci): bump shared-workflows to ${NEW_TAG}"
  fi

  branch="chore/bump-shared-workflows-${NEW_TAG}"
  git push -f origin "HEAD:${branch}"

  title="chore(ci): bump shared-workflows to ${NEW_TAG}"
  body="Automated ${BUMP_LEVEL} bump of \`LerianStudio/github-actions-shared-workflows\` to \`${NEW_TAG}\`.

Generated by [version-propagation](https://github.com/LerianStudio/github-actions-shared-workflows/blob/main/config/version-propagation.yml)."
  if [[ "$force_pr" -eq 1 ]]; then
    body+=$'\n\n> **Major bump**: PR is required (no direct push) so the consumer CI can validate the new contract.'
  fi

  # Labels intentionally omitted — `gh pr create --label X` fails when the
  # label does not exist in the target repo, which varies by consumer.
  url=$(gh pr create \
    --repo "$REPO" \
    --base "$TARGET_BRANCH" \
    --head "$branch" \
    --title "$title" \
    --body "$body")
  action="pr"

  if [[ "$auto_merge" == "true" && "$force_pr" -ne 1 ]]; then
    gh pr merge --auto --squash "$url" || echo "auto-merge enable failed (will stay open)" >&2
  fi
fi

# The direct push succeeded or the replacement PR was just opened above —
# close any older bump PRs this automation left open against the same target
# branch, so consumers don't accumulate one unmerged PR per skipped release.
bot_login_err=""
stale_prs_err=""
cleanup_tmp_files() {
  [[ -z "$bot_login_err" ]] || rm -f -- "$bot_login_err"
  [[ -z "$stale_prs_err" ]] || rm -f -- "$stale_prs_err"
}
trap cleanup_tmp_files EXIT

bot_login=""
if bot_login_err="$(mktemp)" && stale_prs_err="$(mktemp)"; then
  bot_login=$(gh api user --jq '.login' 2>"$bot_login_err") || {
    echo "::warning::could not resolve automation identity, skipping stale PR cleanup:" >&2
    cat "$bot_login_err" >&2
    bot_login=""
  }
else
  echo "::warning::could not create temporary files for stale PR cleanup; skipping cleanup" >&2
fi

current_branch="chore/bump-shared-workflows-${NEW_TAG}"
stale_prs=""
if [[ -n "$bot_login" ]]; then
  # Use `gh api --paginate` (REST pulls list) instead of `gh pr list`, which
  # caps at a fixed --limit — a large target repo could have more open PRs
  # than the cap, silently hiding older bump PRs from this filter. --paginate
  # walks every page, and current_branch/bot_login go through jq --arg rather
  # than being interpolated into the filter string.
  if ! stale_prs=$(gh api "repos/${REPO}/pulls" \
    --method GET \
    --paginate \
    -f state=open \
    -f base="$TARGET_BRANCH" \
    -f per_page=100 \
    2>"$stale_prs_err" | jq -r \
      --arg cur "$current_branch" \
      --arg bot "$bot_login" \
      '.[] | select(.head.ref != $cur and (.head.ref | startswith("chore/bump-shared-workflows-")) and .user.login == $bot) | .number'); then
    echo "::warning::gh api pulls list failed while looking for stale bump PRs:" >&2
    cat "$stale_prs_err" >&2
    stale_prs=""
  fi
fi

if [[ -n "$stale_prs" ]]; then
  while IFS= read -r pr_number; do
    [[ -z "$pr_number" ]] && continue
    echo "closing stale bump PR #${pr_number} (superseded by ${NEW_TAG})" >&2
    gh pr close "$pr_number" --repo "$REPO" \
      --comment "Superseded by \`${NEW_TAG}\`, propagated in this run. Closing to avoid stale bump PRs piling up." \
      || echo "failed to close stale PR #${pr_number}" >&2
  done <<< "$stale_prs"
fi

jq -n --arg repo "$REPO" --arg action "$action" --arg url "$url" \
  '{repo:$repo, action:$action, url:$url}' >&3
