#!/usr/bin/env bash
# Commits staged changes and either pushes directly to the target branch or
# opens a PR. Falls back to PR if direct push fails. Forces PR mode for major
# bumps (caller sets FORCE_PR=1).
#
# Required env:
#   REPO              owner/name
#   TARGET_BRANCH     branch to update
#   NEW_TAG           e.g. v1.28.6
#   BUMP_LEVEL        patch|minor|major
#   FORCE_PR          1 to skip direct push (set for major bumps)
#   AUTO_MERGE        true|false (per-level setting from config)
#   GH_TOKEN          token of the bot (also exported as GITHUB_TOKEN for gh)
#
# Run from the root of the cloned target repo with the version rewrite already
# applied and `git add -A` already executed.
set -euo pipefail

# The caller captures this script's stdout to /tmp/result.json and parses it
# as JSON, so every chatty subprocess (git commit's "[branch sha] msg" line,
# git push progress, gh pr create's URL echo) must NOT leak to stdout.
# Reroute stdout to stderr for the whole script; the final jq writes the
# result via FD 3 (the original stdout).
exec 3>&1 1>&2

: "${REPO:?}" "${TARGET_BRANCH:?}" "${NEW_TAG:?}" "${BUMP_LEVEL:?}" "${GH_TOKEN:?}"
force_pr="${FORCE_PR:-0}"
auto_merge="${AUTO_MERGE:-false}"

# Committer identity and GPG signing are configured globally by the caller
# workflow (see crazy-max/ghaction-import-gpg in version-propagation.yml).
# Do NOT override here — that would replace the signing identity.

msg="chore(ci): bump shared-workflows to ${NEW_TAG}"
if [[ "$BUMP_LEVEL" != "major" ]]; then
  msg+=$'\n\n[skip ci]'
fi

git commit -m "$msg"

action="unknown"
url=""

if [[ "$force_pr" -eq 1 ]]; then
  open_pr=1
else
  if git push origin "HEAD:${TARGET_BRANCH}" 2>/tmp/push.err; then
    action="push"
    open_pr=0
  else
    echo "direct push failed, falling back to PR:" >&2
    cat /tmp/push.err >&2
    open_pr=1
  fi
fi

if [[ "$open_pr" -eq 1 ]]; then
  branch="chore/bump-shared-workflows-${NEW_TAG}"
  git push -f origin "HEAD:${branch}"

  title="chore(ci): bump shared-workflows to ${NEW_TAG}"
  body="Automated ${BUMP_LEVEL} bump of \`LerianStudio/github-actions-shared-workflows\` to \`${NEW_TAG}\`.

Generated by [version-propagation](https://github.com/LerianStudio/github-actions-shared-workflows/blob/main/config/version-propagation.yml)."
  if [[ "$force_pr" -eq 1 ]]; then
    body+=$'\n\n> **Major bump**: PR is required (no direct push) so the consumer CI can validate the new contract.'
  fi

  # Labels intentionally omitted — `gh pr create --label X` fails when the
  # label does not exist in the target repo, which varies by consumer.
  url=$(gh pr create \
    --repo "$REPO" \
    --base "$TARGET_BRANCH" \
    --head "$branch" \
    --title "$title" \
    --body "$body")
  action="pr"

  if [[ "$auto_merge" == "true" && "$force_pr" -ne 1 ]]; then
    gh pr merge --auto --squash "$url" || echo "auto-merge enable failed (will stay open)" >&2
  fi
fi

jq -n --arg repo "$REPO" --arg action "$action" --arg url "$url" \
  '{repo:$repo, action:$action, url:$url}' >&3
